---
title: Your awesome title
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  presentation:
    title: Presentation
    output: true
    permalink: "/:path/"
  uploads:
    title: Uploads
    output: true
email: your-email@example.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
exclude:
- Gemfile.lock
- node_modules
sass:
  sass_dir: _sass
  style: compressed
personal-dark: "#1C213F"
personal-alt: "#D9D4CC"
ace-iot-dark: "#43344F"
ace-iot-alt: "#DBDBDB"
